---
- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: update repositories
      apt:
        update_cache: yes
      changed_when: False

  tasks:
  - include: tasks/gnome.yml    
  - name: install packages
    package:
      name:
        - btop
        - python3-psutil
        - starship
        - zoxide
        - micro
        - fastfetch
        - tldr
        - clamav
        - rclone
        - vlc
        - drawing 
        - libreoffice 
        - firefox
        - chrome-gnome-shell
        - slack
        - xournalpp
      state: latest
      update_cache: yes
    when: ansible_distribution in ["Debian", "Ubuntu"]

  - name: copy .bashrc file
    copy:
     src: files/bashrc
     dest: /home/lion/.bashrc
     owner: lion
     group: lion

  - name: add ansible user
    user:
      name: velociraptor
      system: yes

  - name: set up sudo for ansible user
    copy:
      src: files/sudoer_velociraptor
      dest: /etc/sudoers.d/velociraptor
      owner: root
      group: root
      mode: 0440

  - name: add ansible-pull cron job
    cron:
      name: ansible auto-provision
      user: velociraptor
      minute: "*/10"
      job: ansible-pull -o -U https://github.com/djspatule/ansible-autoconfig.git
