---
- hosts: localhost
  connection: local
  become: true

  vars:
    desktop_user: lion
    desktop_home: "/home/{{ desktop_user }}"
    ansible_sudo_user: velociraptor

  pre_tasks:
    - name: update repositories
      ansible.builtin.apt:
        update_cache: true
        upgrade: dist
      changed_when: false

  tasks:
  - import_tasks: tasks/rclone.yml
  - import_tasks: tasks/packages.yml
  - import_tasks: tasks/gnome.yml
  - import_tasks: tasks/fonts.yml
  - import_tasks: tasks/bashrc.yml
  - import_tasks: tasks/ansible_sudo_user.yml
  - import_tasks: tasks/micro_config.yml

  - name: add ansible-pull cron job
    ansible.builtin.cron:
      name: ansible auto-provision
      user: "{{ ansible_sudo_user }}"
      minute: "*/10"
      job: >-
        ansible-pull -o -U https://github.com/djspatule/ansible-autoconfig.git --vault-password-file ~/secret.txt
