---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: install packages
    package:
      name:
        - btop
        - python3-psutil
        - starship
        - zoxide
        - micro

  - name: copy wallpaper file
    copy:
      src: files/abstract.jpg
      dest: /usr/share/backgrounds/abstract.jpg
      owner: root
      group: root

  - name: set wallpaper
    become_user: lion
    dconf:
      key: "/org/gnome/desktop/background/picture-uri"
      value: "'file:///usr/share/backgrounds/abstract.jpg'"

  - name: set wallpaper position
    become_user: lion
    dconf:
      key: "/org/gnome/desktop/background/picture-options"
      value: "'zoom'"

  - name: set keyboard pref
    become_user: lion
    dconf:
      key: "/org/gnome/desktop/input-sources"
      value: "[('xkb', 'fr')]"

  - name: Configure Dash-to-Dock settings
    become_user: lion
    loop:
      - { key: "/org/gnome/shell/extensions/dash-to-dock/background-opacity", value: "0.8" }
      - { key: "/org/gnome/shell/extensions/dash-to-dock/dash-max-icon-size", value: "48" }
      - { key: "/org/gnome/shell/extensions/dash-to-dock/dock-fixed", value: "false" }
      - { key: "/org/gnome/shell/extensions/dash-to-dock/dock-position", value: "'BOTTOM'" }
      - { key: "/org/gnome/shell/extensions/dash-to-dock/extend-height", value: "false" }
      - { key: "/org/gnome/shell/extensions/dash-to-dock/height-fraction", value: "0.9" }
      - { key: "/org/gnome/shell/extensions/dash-to-dock/isolate-workspaces", value: "true" }
      - { key: "/org/gnome/shell/extensions/dash-to-dock/multi-monitor", value: "true" }
      - { key: "/org/gnome/shell/extensions/dash-to-dock/preferred-monitor", value: "-2" }
      - { key: "/org/gnome/shell/extensions/dash-to-dock/preferred-monitor-by-connector", value: "'DP-3'" }
      - { key: "/org/gnome/shell/extensions/dash-to-dock/show-mounts", value: "false" }
      - { key: "/org/gnome/shell/extensions/dash-to-dock/show-mounts-network", value: "false" }
      - { key: "/org/gnome/shell/extensions/dash-to-dock/show-mounts-only-mounted", value: "true" }
    loop_control:
      label: "{{ item.key }}"
    community.general.dconf:
      key: "{{ item.key }}"
      value: "{{ item.value }}"

  - name: Configure GNOME interface settings
    become_user: lion
    loop:
      - { key: "/org/gnome/desktop/interface/accent-color", value: "'green'" }
      - { key: "/org/gnome/desktop/interface/clock-format", value: "'24h'" }
      - { key: "/org/gnome/desktop/interface/clock-show-weekday", value: "true" }
      - { key: "/org/gnome/desktop/interface/color-scheme", value: "'prefer-dark'" }
      - { key: "/org/gnome/desktop/interface/cursor-theme", value: "'Yaru'" }
      - { key: "/org/gnome/desktop/interface/font-antialiasing", value: "'grayscale'" }
      - { key: "/org/gnome/desktop/interface/font-hinting", value: "'slight'" }
      - { key: "/org/gnome/desktop/interface/font-name", value: "'Ubuntu Sans 11'" }
      - { key: "/org/gnome/desktop/interface/gtk-theme", value: "'Yaru'" }
      - { key: "/org/gnome/desktop/interface/icon-theme", value: "'Yaru'" }
      - { key: "/org/gnome/desktop/interface/locate-pointer", value: "true" }
      - { key: "/org/gnome/desktop/interface/show-battery-percentage", value: "true" }
      - { key: "/org/gnome/desktop/interface/toolkit-accessibility", value: "false" }
    loop_control:
      label: "{{ item.key }}"
    community.general.dconf:
      key: "{{ item.key }}"
      value: "{{ item.value }}"

  - name: copy .bashrc file
    copy:
     src: files/bashrc
     dest: /home/lion/.bashrc
     owner: lion
     group: lion

  - name: add ansible user
    user:
      name: velociraptor
      system: yes

  - name: set up sudo for ansible user
    copy:
      src: files/sudoer_velociraptor
      dest: /etc/sudoers.d/velociraptor
      owner: root
      group: root
      mode: 0440

  - name: add ansible-pull cron job
    cron:
      name: ansible auto-provision
      user: velociraptor
      minute: "*/10"
      job: ansible-pull -o -U https://github.com/djspatule/ansible-autoconfig.git
