---
autoconfig_repo_url: https://github.com/djspatule/ansible-autoconfig.git
autoconfig_branch: server-bootstrap
autoconfig_repo_dir: /opt/ansible-pull
autoconfig_playbook: server_core.yml
autoconfig_timer_name: autoconfig-pull
autoconfig_on_calendar: daily
autoconfig_randomized_delay: 30m
autoconfig_persistent: true
autoconfig_vault_password_file: ""
