---
- name: add ansible user
  ansible.builtin.user:
    name: "{{ automation_user }}"
    system: true

- name: set up sudo for ansible user
  ansible.builtin.copy:
    dest: "/etc/sudoers.d/{{ automation_user }}"
    owner: root
    group: root
    mode: "0440"
    content: "{{ automation_user }} ALL=(ALL) NOPASSWD: ALL"
