---
- name: add ansible user
  ansible.builtin.user:
    name: "{{ cron_sudo_user }}"
    system: true

- name: set up sudo for ansible user
  ansible.builtin.copy:
    dest: "/etc/sudoers.d/{{ cron_sudo_user }}"
    owner: root
    group: root
    mode: "0440"
    content: "{{ cron_sudo_user }} ALL=(ALL) NOPASSWD: ALL"
