- name: Install system build dependencies
  apt:
    name:
      - build-essential
      - curl
      - git
      - wl-clipboard
      - libxkbcommon-dev
      - libdbus-1-dev
      - libssl-dev
      - libwxgtk3.2-dev
    state: present
    update_cache: yes

- name: Ensure Rust toolchain (rustup) is installed
  shell: |
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
    source "{{ ansible_env.HOME }}/.cargo/env"
  args:
    creates: "{{ ansible_env.HOME }}/.cargo/bin/rustc"
  environment:
    HOME: "{{ ansible_env.HOME }}"

- name: Install cargo-make at specified version
  become_user: "{{ ansible_user }}"
  shell: |
    source "{{ ansible_env.HOME }}/.cargo/env"
    cargo install --force cargo-make --version {{ cargo_make_version }}
  args:
    creates: "{{ ansible_env.HOME }}/.cargo/bin/cargo-make"

- name: Clone Espanso repository
  git:
    repo: "https://github.com/federico-terzi/espanso.git"
    dest: "{{ espanso_src }}"
    update: yes
  become_user: "{{ ansible_user }}"

- name: Compile Espanso binary for Wayland (no X11)
  shell: >
    source "{{ ansible_env.HOME }}/.cargo/env"
    cd "{{ espanso_src }}"
    cargo make --profile release --env NO_X11=true build-binary
  args:
    chdir: "{{ espanso_src }}"
  become_user: "{{ ansible_user }}"

- name: Move espanso binary to /usr/local/bin
  copy:
    src: "{{ espanso_src }}/target/release/espanso"
    dest: /usr/local/bin/espanso
    mode: '0755'

- name: Grant CAP_DAC_OVERRIDE capability to espanso binary
  command: setcap "cap_dac_override+p" /usr/local/bin/espanso

- name: Register Espanso systemd service for user
  become_user: "{{ ansible_user }}"
  command: espanso service register

- name: Start Espanso service
  become_user: "{{ ansible_user }}"
  command: espanso start

- name: Confirm Espanso is running
  become_user: "{{ ansible_user }}"
  command: espanso status
  register: espanso_status

- name: Show Espanso status
  debug:
    var: espanso_status.stdout_lines

- name: Ensure espanso config directory exists
  become_user: "{{ ansible_user }}"
  file:
    path: "{{ ansible_env.HOME }}/.config/espanso/match"
    state: directory
    mode: '0700'

- name: Deploy espanso base.yml config
  become_user: "{{ ansible_user }}"
  copy:
    src: files/espanso/base.yml
    dest: "{{ ansible_env.HOME }}/.config/espanso/match/base.yml"
    mode: '0600'
