# tasks/micro_config.yml (as a task file)
- name: Ensure plugin directory exists
  file:
    path: "{{ ansible_env.HOME }}/.config/micro/plug/search"
    state: directory
    mode: '0755'

- name: Download search.lua plugin
  get_url:
    url: "https://raw.githubusercontent.com/dmaluka/micro-search/master/search.lua"
    dest: "{{ ansible_env.HOME }}/.config/micro/plug/search/search.lua"
    mode: '0644'