- name: install apt packages
  package:
    name:
      # CLI utilities
      - btop
      - python3-psutil
      - micro
      - fastfetch
      - pdfgrep
      - tldr
      - ncdu
      - mc
      - bat
      - clamav
      - rclone
      - cowsay
      - asciiquarium
      - oneko
      # Media
      - vlc
      - drawing
      # Office
      - libreoffice
      - onlyoffice
      - firefox
      - slack
      - xournalpp
      # GNOME
      - gnome-tweaks
      - gnome-shell-extensions
      - gnome-shell-extension-manager
    state: latest
    update_cache: yes
  when: ansible_distribution in ["Debian", "Ubuntu"]

- name: Install snap packages
  community.general.snap:
    name: "{{ item }}"
    state: present
  loop:
    - tigervnc
    - colorwall
    - slack
    - spotify
    - sublime-text
    - vivaldi
  when: ansible_distribution in ["Debian", "Ubuntu"]

- name: Install Flatpak packages
  community.general.flatpak:
    name: "{{ item }}"
    state: present
  loop:
    - zoom
    - eyedropper
    - org.flameshot.Flameshot
    - betterbird
  when: ansible_distribution in ["Debian", "Ubuntu"]

- name: Allow org.flameshot.Flameshot to take screenshots
  ansible.builtin.command: >
    flatpak permission-set screenshot screenshot org.flameshot.Flameshot yes
  when: ansible_distribution in ["Debian", "Ubuntu"]
