- name: install apt packages
  package:
    name:
      - btop
      - python3-psutil
      - micro
      - fastfetch
      - tldr
      - ncdu
      - mc
      - bat
      - clamav
      - rclone
      - vlc
      - drawing
      - libreoffice
      - firefox
      - chrome-gnome-shell
      - slack
      - xournalpp
      - fastfetch
      - pdfgrep
      - gnome-tweaks
      - gnome-shell-extensions
      - gnome-shell-extension-manager
    state: latest
    update_cache: yes
  when: ansible_distribution in ["Debian", "Ubuntu"]

- name: Install snap packages
  community.general.snap:
    name: "{{ item }}"
    state: present
  loop:
    - tigervnc
    - colorwall
    - slack
    - spotify
    - sublime-text
    - vivaldi
  when: ansible_distribution in ["Debian", "Ubuntu"]