---
# rclone config

- name: Ensure rclone config directory exists
  file:
    path: /home/lion/.config/rclone
    state: directory
    owner: lion
    group: lion
    mode: '0700'

- name: Check if /home/lion/Google Drive Perso exists
  stat:
    path: "/home/lion/Google Drive Perso"
  register: gdrive_mountpoint

- name: Check if /home/lion/Google Drive Perso is a mountpoint
  command: mountpoint -q "/home/lion/Google Drive Perso"
  register: gdrive_is_mount
  failed_when: false
  changed_when: false
  when: gdrive_mountpoint.stat.exists

- name: Create /home/lion/Google Drive Perso directory if not a mount
  file:
    path: "/home/lion/Google Drive Perso"
    state: directory
    owner: lion
    group: lion
    mode: '0755'
  when:
    - not gdrive_mountpoint.stat.exists
    - gdrive_is_mount.rc != 0

- name: Copy rclone config
  copy:
    src: files/rclone.conf
    dest: /home/lion/.config/rclone/rclone.conf
    owner: lion
    group: lion
    mode: '0600'

- name: Copy rclone mount script
  copy:
    src: files/rclone_mount.sh
    dest: /home/lion/rclone_mount.sh
    owner: lion
    group: lion
    mode: '0755'

- name: Add rclone mount to cron
  cron:
    name: "Mount Google Drive Perso with rclone"
    user: lion
    job: "/home/lion/rclone_mount.sh"
    state: present
