- name: Configure Betterbird with minimal profile
  tags: betterbird
  become: true
  become_user: "{{ desktop_user | default('lion') }}"
  vars:
    bb_root_preferred: "/home/{{ desktop_user | default('lion') }}/.var/app/eu.betterbird.Betterbird/thunderbird"
    bb_root_alt: "/home/{{ desktop_user | default('lion') }}/.var/app/eu.betterbird.Betterbird/.thunderbird"
    bb_root: "{{ bb_root_preferred }}"
    bb_profile: "c38hedqq.default-default"
    bb_src: "{{ role_path }}/files/users/lion/betterbird_minimal"
  block:
    - name: Ensure Betterbird is not running (avoid locked profile files)
      ansible.builtin.command: flatpak kill eu.betterbird.Betterbird
      changed_when: false
      failed_when: false

    - name: Detect Betterbird profile root paths
      ansible.builtin.stat:
        path: "{{ item }}"
      register: bb_root_stats
      loop:
        - "{{ bb_root_preferred }}"
        - "{{ bb_root_alt }}"

    - name: Choose Betterbird profile root based on existence
      ansible.builtin.set_fact:
        bb_root: >-
          {{ (bb_root_stats.results[0].stat.exists | default(false))
                | ternary(bb_root_preferred,
                         (bb_root_stats.results[1].stat.exists | default(false))
                           | ternary(bb_root_alt, bb_root_preferred)) }}

    - name: Ensure Betterbird profile dir exists
      file:
        path: "{{ bb_root }}/{{ bb_profile }}"
        state: directory
        mode: "0700"

    - name: Find files for minimal Betterbird config
      ansible.builtin.find:
        paths: "{{ bb_src }}"
        recurse: true
        file_type: any
      register: bb_src_items

    - name: Ensure destination directories exist for minimal config (excluding filters subtree)
      ansible.builtin.file:
        path: "{{ bb_root }}/{{ bb_profile }}/{{ item.path | regex_replace('^' + bb_src + '/', '') }}"
        state: directory
        mode: "0700"
      loop: "{{ bb_src_items.files | selectattr('isdir', 'defined') | selectattr('isdir') | rejectattr('path', 'search', '/filters(/|$)') | list }}"

    - name: Copy minimal Betterbird config files (excluding filters subtree)
      ansible.builtin.copy:
        src: "{{ item.path }}"
        dest: "{{ bb_root }}/{{ bb_profile }}/{{ item.path | regex_replace('^' + bb_src + '/', '') }}"
        owner: "{{ desktop_user | default('lion') }}"
        group: "{{ desktop_user | default('lion') }}"
        mode: preserve
      loop: "{{ bb_src_items.files | rejectattr('isdir', 'defined') | rejectattr('path', 'search', '/filters(/|$)') | list }}"

    - name: Ensure profiles.ini points to our profile
      copy:
        dest: "{{ bb_root }}/profiles.ini"
        mode: "0644"
        content: |
          [Profile0]
          Name=default
          IsRelative=1
          Path={{ bb_profile }}
          Default=1

          [General]
          StartWithLastProfile=1
          Version=2

    - name: Remove installs.ini in selected root so profiles.ini is honored
      ansible.builtin.file:
        path: "{{ bb_root }}/installs.ini"
        state: absent

    - name: Also remove installs.ini in the alternate root if present
      ansible.builtin.file:
        path: "{{ bb_root_alt }}/installs.ini"
        state: absent
      ignore_errors: true

    - name: If installs.ini exists, discover its Install section (selected root)
      ansible.builtin.shell: |
        set -eo pipefail
        [ -f "{{ bb_root }}/installs.ini" ] || exit 0
        awk -F'[][]' '/^\[Install/{print $2; exit}' "{{ bb_root }}/installs.ini"
      args:
        executable: /bin/bash
      register: bb_install_section
      changed_when: false
      failed_when: false

    - name: Set Default in installs.ini to selected profile (selected root)
      when: (bb_install_section.stdout | length) > 0
      ansible.builtin.ini_file:
        path: "{{ bb_root }}/installs.ini"
        section: "{{ bb_install_section.stdout }}"
        option: Default
        value: "{{ bb_profile }}"
        mode: "0644"

    - name: Lock installs.ini to selected profile (selected root)
      when: (bb_install_section.stdout | length) > 0
      ansible.builtin.ini_file:
        path: "{{ bb_root }}/installs.ini"
        section: "{{ bb_install_section.stdout }}"
        option: Locked
        value: "1"
        mode: "0644"

    - name: If installs.ini exists, discover its Install section (alternate root)
      ansible.builtin.shell: |
        set -eo pipefail
        [ -f "{{ bb_root_alt }}/installs.ini" ] || exit 0
        awk -F'[][]' '/^\[Install/{print $2; exit}' "{{ bb_root_alt }}/installs.ini"
      args:
        executable: /bin/bash
      register: bb_install_section_alt
      changed_when: false
      failed_when: false

    - name: Set Default in installs.ini to selected profile (alternate root)
      when: (bb_install_section_alt.stdout | length) > 0
      ansible.builtin.ini_file:
        path: "{{ bb_root_alt }}/installs.ini"
        section: "{{ bb_install_section_alt.stdout }}"
        option: Default
        value: "{{ bb_profile }}"
        mode: "0644"

    - name: Lock installs.ini to selected profile (alternate root)
      when: (bb_install_section_alt.stdout | length) > 0
      ansible.builtin.ini_file:
        path: "{{ bb_root_alt }}/installs.ini"
        section: "{{ bb_install_section_alt.stdout }}"
        option: Locked
        value: "1"
        mode: "0644"

    - name: Ensure filter directories exist in the selected profile
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: "0700"
      loop:
        - "{{ bb_root }}/{{ bb_profile }}/ImapMail/imap.gmail.com"
        - "{{ bb_root }}/{{ bb_profile }}/Mail/Local Folders"

    - name: Copy msgFilterRules.dat for IMAP account if present
      ansible.builtin.copy:
        src: "{{ bb_src }}/filters/home/lion/.var/app/eu.betterbird.Betterbird/.thunderbird/{{ bb_profile }}/ImapMail/imap.gmail.com/msgFilterRules.dat"
        dest: "{{ bb_root }}/{{ bb_profile }}/ImapMail/imap.gmail.com/msgFilterRules.dat"
        owner: "{{ desktop_user | default('lion') }}"
        group: "{{ desktop_user | default('lion') }}"
        mode: "0644"
      ignore_errors: true

    - name: Copy msgFilterRules.dat for Local Folders if present
      ansible.builtin.copy:
        src: "{{ bb_src }}/filters/home/lion/.var/app/eu.betterbird.Betterbird/.thunderbird/{{ bb_profile }}/Mail/Local Folders/msgFilterRules.dat"
        dest: "{{ bb_root }}/{{ bb_profile }}/Mail/Local Folders/msgFilterRules.dat"
        owner: "{{ desktop_user | default('lion') }}"
        group: "{{ desktop_user | default('lion') }}"
        mode: "0644"
      ignore_errors: true

    - name: Debug Betterbird profile state
      ansible.builtin.shell: |
        set -eu
        echo "bb_root_preferred={{ bb_root_preferred }}"
        echo "bb_root_alt={{ bb_root_alt }}"
        echo "bb_root={{ bb_root }}"
        echo "bb_profile={{ bb_profile }}"
        echo "===== ls -la {{ bb_root }}" && ls -la "{{ bb_root }}" || true
        echo "===== profiles.ini" && (cat "{{ bb_root }}/profiles.ini" || echo "profiles.ini missing")
        echo "===== installs.ini (selected root)" && (cat "{{ bb_root }}/installs.ini" || echo "installs.ini missing (expected)")
        echo "===== installs.ini (alternate root)" && (cat "{{ bb_root_alt }}/installs.ini" || echo "installs.ini missing (expected)")
        echo "===== profile directories" && (find "{{ bb_root }}" -maxdepth 1 -mindepth 1 -type d -printf '%f\n' | sort || true)
      args:
        executable: /bin/bash
      register: betterbird_debug
      changed_when: false
      failed_when: false

    - name: Show Betterbird debug info
      ansible.builtin.debug:
        msg: "{{ betterbird_debug.stdout }}"
