---
# roles/workstation/tasks/betterbird.yml
- name: Configure Betterbird (Flatpak profile)
  tags: betterbird
  become: true
  become_user: "{{ desktop_user | default('lion') }}"
  vars:
    bb_root: "/home/{{ desktop_user | default('lion') }}/.var/app/eu.betterbird.Betterbird/.thunderbird"
    bb_profile: "c38hedqq.default-default"   # adjust if different on target
  block:
    - name: Ensure Betterbird profile dir exists
      file:
        path: "{{ bb_root }}/{{ bb_profile }}"
        state: directory
        mode: "0700"

    - name: Deploy Betterbird minimal config by copying folder
      ansible.builtin.copy:
        src: "{{ role_path }}/files/betterbird_minimal/"
        dest: "{{ bb_root }}/{{ bb_profile }}/"
        owner: "{{ desktop_user | default('lion') }}"
        group: "{{ desktop_user | default('lion') }}"
        mode: preserve
      # become: true
      # become_user: lion


    - name: Ensure profiles.ini points to our profile
      copy:
        dest: "{{ bb_root }}/profiles.ini"
        mode: "0644"
        content: |
          [Profile0]
          Name=default
          IsRelative=1
          Path={{ bb_profile }}
          Default=1

          [General]
          StartWithLastProfile=1
          Version=2
