---
- Infrastructure:
    - Homepage:
        icon: homepage.png
        href: /
        description: Server dashboard
        server: local-docker
        container: homepage
        showStats: true
        siteMonitor: http://homepage:3000/
    - BentoPDF:
        icon: mdi-file-pdf-box
        href: http://192.168.1.100:8080/
        description: Privacy-first PDF toolkit
        server: local-docker
        container: bentopdf
        showStats: true
        siteMonitor: http://bentopdf:8080/
